name: filekeeper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Go modules
      run: |
        go mod init github.com/ykargin/filekeeper
        go mod tidy

    - name: Install dependencies
      run: go get -v gopkg.in/yaml.v3

    - name: Build
      run: go build -v -o filekeeper .

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: filekeeper
        path: filekeeper
