# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: filekeeper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go get -v gopkg.in/yaml.v3

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v -o filekeeper

    - name: Format check
      run: |
        if [ "$(gofmt -d . | wc -l)" -gt 0 ]; then
          echo "Code formatting issues found:"
          gofmt -d .
          exit 1
        fi

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: filekeeper
        path: filekeeper
