# Updated workflow for tag releases
name: filekeeper

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_name: filekeeper-linux-amd64
            asset_name: filekeeper-linux-amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Debug info
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "GitHub event name: ${{ github.event_name }}"
        echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Go modules
      run: |
        go mod init github.com/ykargin/filekeeper
        go mod tidy

    - name: Install dependencies
      run: go get -v gopkg.in/yaml.v3

    - name: Build
      run: go build -v -o ${{ matrix.artifact_name }} .

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    # Уточняем условие, делаем его более явным
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Release Info
        run: |
          echo "Creating release for tag: ${{ github.ref_name }}"
          echo "Full ref: ${{ github.ref }}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: filekeeper-linux-amd64
          path: ./

      - name: List files
        run: ls -la ./

      - name: Make binary executable
        run: chmod +x ./filekeeper-linux-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./filekeeper-linux-amd64
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
